import { TimelineNode, UniverseTrack } from './types';

export const UNIVERSE_TRACKS: UniverseTrack[] = [
  {
    id: 'spider',
    label: 'SPIDER-BRANCH',
    code: 'C-96283 / 120703',
    designation: 'C-96283 / 120703: SPIDER CONTINUITIES',
    y: 680,
    color: '#FF3B30',
    glowColor: '#FFA19B',
    startX: 40,
    endX: 3300,
    description: 'Raimi and Webb legacy arachnid continuities, converging through dimensional colliders and multiversal spell fractures.',
    columnIndex: 0,
  },
  {
    id: '10005',
    label: 'LEGACY MUTANT',
    code: 'C-10005',
    designation: 'C-10005: LEGACY MUTANT CONTINUITY',
    y: 470,
    color: '#00A3FF',
    glowColor: '#70CFFF',
    startX: 40,
    endX: 3300,
    description: 'Fox continuity harboring the mutant genome, bifurcated by 1973 time travel and culminating in anchor being dissolution.',
    columnIndex: 1,
  },
  {
    id: '616',
    label: 'SACRED TIMELINE',
    code: 'C-616',
    designation: 'C-616: SACRED MCU CONTINUITY',
    y: 220,
    color: '#F5A623',
    glowColor: '#FFD082',
    startX: 40,
    endX: 3300,
    description: 'The prime continuity curated by He Who Remains and the TVA, expanding into the Multiverse Saga following temporal liberation.',
    columnIndex: 2,
  },
];

export const ERA_DIVIDERS = [
  { id: 'era-roots', label: 'ERA I: DAWN OF MODERN CONTINUITY', years: '2000 — 2007', y: 50 },
  { id: 'era-p1-2', label: 'ERA II: AVENGERS INITIATIVE & EXPANSION', years: '2008 — 2015', y: 650 },
  { id: 'era-p3', label: 'ERA III: THE INFINITY SAGA CLIMAX', years: '2016 — 2019', y: 1950 },
  { id: 'era-multi', label: 'ERA IV: THE MULTIVERSE CONVERGENCE', years: '2021 — 2024+', y: 2850 },
];

export const INITIAL_TIMELINE_NODES: TimelineNode[] = [
  // ==========================================
  // ERA I: 2000 - 2007 (PRE-MCU ROOTS)
  // ==========================================
  {
    id: 'f1',
    title: 'X-MEN',
    year: '2000',
    uni: '10005',
    universeCode: 'C-10005',
    color: '#00A3FF',
    glowColor: '#70CFFF',
    x: 120,
    y: 470,
    verticalY: 90,
    columnIndex: 1,
    runtime: '104m',
    runtimeMinutes: 104,
    seen: false,
    era: 'Dawn of Continuity',
    posterUrl: 'https://image.tmdb.org/t/p/w500/bRDAc4GogyS9ci3ow7UnInOcriN.jpg',
    desc: 'Mutants step out of the shadows. Magneto constructs a mutation engine atop the Statue of Liberty, thwarted by Charles Xavier and the X-Men.',
    anchorEvent: 'Liberty Island Confrontation',
    incursionRisk: 'Stable',
    keyVariants: ['Hugh Jackman (Logan / Wolverine)', 'Patrick Stewart (Charles Xavier)', 'Ian McKellen (Erik Lehnsherr)'],
  },
  {
    id: 's1',
    title: 'SPIDER-MAN',
    year: '2002',
    uni: 'spider',
    universeCode: 'C-96283',
    color: '#FF3B30',
    glowColor: '#FFA19B',
    x: 250,
    y: 680,
    verticalY: 190,
    columnIndex: 0,
    runtime: '121m',
    runtimeMinutes: 121,
    seen: false,
    era: 'Dawn of Continuity',
    posterUrl: 'https://image.tmdb.org/t/p/w500/or6XJBVpcEbIkma0V9zshnbEtx4.jpg',
    desc: 'Peter Parker is bitten by a genetically engineered spider. After Uncle Ben is slain, Peter embraces responsibility, battling Norman Osborn.',
    anchorEvent: 'Queensbridge Arachnid Genesis',
    incursionRisk: 'Stable',
    keyVariants: ['Tobey Maguire (Peter Parker / Spider-Man)', 'Willem Dafoe (Norman Osborn / Green Goblin)'],
  },
  {
    id: 'f_x2',
    title: 'X2: X-MEN UNITED',
    year: '2003',
    uni: '10005',
    universeCode: 'C-10005',
    color: '#00A3FF',
    glowColor: '#70CFFF',
    x: 370,
    y: 470,
    verticalY: 290,
    columnIndex: 1,
    runtime: '134m',
    runtimeMinutes: 134,
    seen: false,
    era: 'Dawn of Continuity',
    posterUrl: 'https://image.tmdb.org/t/p/w500/bst4alFUXCxISwdRUKSMhhkrX1M.jpg',
    desc: 'Colonel William Stryker invades the Xavier Institute. Mutants unite with Magneto at Alkali Lake, culminating in Jean Grey’s catastrophic sacrifice.',
    anchorEvent: 'Alkali Lake Dam Breach',
    incursionRisk: 'Stable',
    keyVariants: ['Hugh Jackman (Logan)', 'Famke Janssen (Jean Grey)', 'Brian Cox (William Stryker)'],
  },
  {
    id: 's2',
    title: 'SPIDER-MAN 2',
    year: '2004',
    uni: 'spider',
    universeCode: 'C-96283',
    color: '#FF3B30',
    glowColor: '#FFA19B',
    x: 490,
    y: 680,
    verticalY: 390,
    columnIndex: 0,
    runtime: '127m',
    runtimeMinutes: 127,
    seen: false,
    nexus: true,
    era: 'Dawn of Continuity',
    posterUrl: 'https://image.tmdb.org/t/p/w500/aGuvNAaaZuWXYQQ6N2v7DeuP6mB.jpg',
    desc: 'Dr. Otto Octavius’s fusion reactor collapses into a rogue singularity. Directly intersects with Earth-616 during the botched Kof-Kol spell.',
    anchorEvent: 'Tritium Fusion Incident',
    incursionRisk: 'Catastrophic',
    keyVariants: ['Tobey Maguire (Peter Parker)', 'Alfred Molina (Dr. Otto Octavius)'],
    connections: [
      {
        targetId: 'm5',
        targetTitle: 'Spider-Man: No Way Home',
        reason: 'Otto Octavius and Tobey Maguire variant pulled across reality into Sacred 616.',
      },
    ],
  },
  {
    id: 'f_x3',
    title: 'X-MEN: THE LAST STAND',
    year: '2006',
    uni: '10005',
    universeCode: 'C-10005',
    color: '#00A3FF',
    glowColor: '#70CFFF',
    x: 610,
    y: 470,
    verticalY: 490,
    columnIndex: 1,
    runtime: '104m',
    runtimeMinutes: 104,
    seen: false,
    era: 'Dawn of Continuity',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gp4zlj7wgbiofLMNsTPndMuO3PN.jpg',
    desc: 'The emergence of a mutant cure ignites total conflict at Alcatraz. Jean Grey manifests as the Dark Phoenix, forced to be terminated by Logan.',
    anchorEvent: 'Alcatraz Phoenix Cataclysm',
    incursionRisk: 'Severe',
    keyVariants: ['Hugh Jackman (Logan)', 'Famke Janssen (Dark Phoenix)', 'Kelsey Grammer (Hank McCoy / Beast)'],
  },
  {
    id: 's3',
    title: 'SPIDER-MAN 3',
    year: '2007',
    uni: 'spider',
    universeCode: 'C-96283',
    color: '#FF3B30',
    glowColor: '#FFA19B',
    x: 730,
    y: 680,
    verticalY: 590,
    columnIndex: 0,
    runtime: '139m',
    runtimeMinutes: 139,
    seen: false,
    era: 'Dawn of Continuity',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qFmwhVUoUSXjkKRmca5yGDEXBIj.jpg',
    desc: 'An alien Klyntar symbiote bonds with Peter Parker before attaching to Eddie Brock. Sandman reconciles with Peter over Uncle Ben’s death.',
    anchorEvent: 'Symbiote Resonance Resonance',
    incursionRisk: 'Stable',
    keyVariants: ['Tobey Maguire (Peter Parker)', 'Thomas Haden Church (Flint Marko / Sandman)', 'Topher Grace (Eddie Brock / Venom)'],
    connections: [
      {
        targetId: 'm5',
        targetTitle: 'Spider-Man: No Way Home',
        reason: 'Flint Marko (Sandman) displaced into Earth-616 multiversal rift.',
      },
    ],
  },

  // ==========================================
  // ERA II: 2008 - 2015 (PHASE 1 & PHASE 2)
  // ==========================================
  {
    id: 'm1',
    title: 'IRON MAN',
    year: '2008',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 860,
    y: 220,
    verticalY: 690,
    columnIndex: 2,
    runtime: '126m',
    runtimeMinutes: 126,
    seen: true,
    phase: 'Phase 1',
    era: 'Avengers Initiative',
    posterUrl: 'https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg',
    desc: 'The genesis of the Sacred Timeline’s Heroic Age. Tony Stark builds the Mark I to escape Afghan captivity and reveals his identity to humanity.',
    anchorEvent: 'Genesis of the Heroic Age',
    incursionRisk: 'Stable',
    keyVariants: ['Robert Downey Jr. (Tony Stark / Iron Man)', 'Gwyneth Paltrow (Pepper Potts)', 'Samuel L. Jackson (Nick Fury)'],
  },
  {
    id: 'm_hulk',
    title: 'THE INCREDIBLE HULK',
    year: '2008',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 960,
    y: 220,
    verticalY: 790,
    columnIndex: 2,
    runtime: '112m',
    runtimeMinutes: 112,
    seen: false,
    phase: 'Phase 1',
    era: 'Avengers Initiative',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gKzYx79y0AQTL4UAk1cBQJ3nvrm.jpg',
    desc: 'Dr. Bruce Banner searches for a cure to gamma radiation. Emil Blonsky undergoes illicit Super Soldier transfusion to become the Abomination.',
    anchorEvent: 'Harlem Gamma Resonance',
    incursionRisk: 'Stable',
    keyVariants: ['Edward Norton (Bruce Banner / Hulk)', 'Tim Roth (Emil Blonsky / Abomination)'],
  },
  {
    id: 'f_fc',
    title: 'X-MEN: FIRST CLASS',
    year: '2011',
    uni: '10005',
    universeCode: 'C-10005',
    color: '#00A3FF',
    glowColor: '#70CFFF',
    x: 1080,
    y: 470,
    verticalY: 890,
    columnIndex: 1,
    runtime: '132m',
    runtimeMinutes: 132,
    seen: false,
    era: 'Avengers Initiative',
    posterUrl: 'https://image.tmdb.org/t/p/w500/hNEokmUke0dazoBhttFN0o3L7Xv.jpg',
    desc: '1962: During the height of the Cold War, Charles Xavier and Erik Lehnsherr recruit young mutants to avert nuclear catastrophe engineered by the Hellfire Club.',
    anchorEvent: '1962 Cuban Missile Convergence',
    incursionRisk: 'Stable',
    keyVariants: ['James McAvoy (Charles Xavier)', 'Michael Fassbender (Erik Lehnsherr)', 'Jennifer Lawrence (Raven / Mystique)'],
  },
  {
    id: 'm_thor1',
    title: 'THOR',
    year: '2011',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 1180,
    y: 220,
    verticalY: 990,
    columnIndex: 2,
    runtime: '115m',
    runtimeMinutes: 115,
    seen: false,
    phase: 'Phase 1',
    era: 'Avengers Initiative',
    posterUrl: 'https://image.tmdb.org/t/p/w500/prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg',
    desc: 'Banished to Midgard without his powers, Thor proves worthy of Mjolnir, stopping Loki’s scheme to eradicate Jotunheim and shatter Asgard’s realm.',
    anchorEvent: 'Bifrost Fracturing Incident',
    incursionRisk: 'Stable',
    keyVariants: ['Chris Hemsworth (Thor Odinson)', 'Tom Hiddleston (Loki Laufeyson)', 'Anthony Hopkins (Odin)'],
  },
  {
    id: 'm_cap1',
    title: 'CAPTAIN AMERICA: FIRST AVENGER',
    year: '2011',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 1280,
    y: 220,
    verticalY: 1090,
    columnIndex: 2,
    runtime: '124m',
    runtimeMinutes: 124,
    seen: false,
    phase: 'Phase 1',
    era: 'Avengers Initiative',
    posterUrl: 'https://image.tmdb.org/t/p/w500/vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg',
    desc: '1942: Steve Rogers is transformed by Project Rebirth. Foils the Red Skull’s Tesseract-powered super-weapons before crashing into Arctic ice for 70 years.',
    anchorEvent: 'Project Rebirth & Valkyrie Submersion',
    incursionRisk: 'Stable',
    keyVariants: ['Chris Evans (Steve Rogers / Captain America)', 'Hugo Weaving (Johann Schmidt / Red Skull)', 'Sebastian Stan (Bucky Barnes)'],
  },
  {
    id: 'm2',
    title: 'THE AVENGERS',
    year: '2012',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 1400,
    y: 220,
    verticalY: 1190,
    columnIndex: 2,
    runtime: '143m',
    runtimeMinutes: 143,
    seen: true,
    phase: 'Phase 1',
    era: 'Avengers Initiative',
    posterUrl: 'https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
    desc: 'Earth’s Mightiest Heroes assemble to halt Loki and the Chitauri armada in Manhattan. The first cosmic crossroad for the Space and Mind Stones.',
    anchorEvent: 'Battle of New York',
    incursionRisk: 'Moderate',
    keyVariants: ['Robert Downey Jr. (Iron Man)', 'Chris Evans (Captain America)', 'Chris Hemsworth (Thor)', 'Mark Ruffalo (Hulk)', 'Scarlett Johansson (Black Widow)'],
  },
  {
    id: 's_asm1',
    title: 'THE AMAZING SPIDER-MAN',
    year: '2012',
    uni: 'spider',
    universeCode: 'C-120703',
    color: '#FF3B30',
    glowColor: '#FFA19B',
    x: 1440,
    y: 680,
    verticalY: 1290,
    columnIndex: 0,
    runtime: '136m',
    runtimeMinutes: 136,
    seen: false,
    era: 'Avengers Initiative',
    posterUrl: 'https://image.tmdb.org/t/p/w500/jexoNYnPd6vVrmygwF6QZmWPFdu.jpg',
    desc: 'Peter Parker discovers his father’s cross-species genetics research at Oscorp. Curt Connors becomes the Lizard, releasing serum over Manhattan.',
    anchorEvent: 'Oscorp Tower Cloud Dispersion',
    incursionRisk: 'Stable',
    keyVariants: ['Andrew Garfield (Peter Parker / Spider-Man)', 'Emma Stone (Gwen Stacy)', 'Rhys Ifans (Dr. Curt Connors / Lizard)'],
  },
  {
    id: 'm_ws',
    title: 'THE WINTER SOLDIER',
    year: '2014',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 1560,
    y: 220,
    verticalY: 1390,
    columnIndex: 2,
    runtime: '136m',
    runtimeMinutes: 136,
    seen: false,
    phase: 'Phase 2',
    era: 'Cosmic Expansion',
    posterUrl: 'https://image.tmdb.org/t/p/w500/tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg',
    desc: 'Hydra infiltration of S.H.I.E.L.D. is exposed. Steve Rogers faces his brainwashed brother-in-arms Bucky Barnes as Project Insight helicarriers target millions.',
    anchorEvent: 'Triskelion Helicarrier Collapse',
    incursionRisk: 'Stable',
    keyVariants: ['Chris Evans (Captain America)', 'Sebastian Stan (The Winter Soldier)', 'Scarlett Johansson (Black Widow)', 'Robert Redford (Alexander Pierce)'],
  },
  {
    id: 's_asm2',
    title: 'THE AMAZING SPIDER-MAN 2',
    year: '2014',
    uni: 'spider',
    universeCode: 'C-120703',
    color: '#FF3B30',
    glowColor: '#FFA19B',
    x: 1640,
    y: 680,
    verticalY: 1490,
    columnIndex: 0,
    runtime: '142m',
    runtimeMinutes: 142,
    seen: false,
    nexus: true,
    era: 'Cosmic Expansion',
    posterUrl: 'https://image.tmdb.org/t/p/w500/bU7nTmvmy0h3VUP01v1T2imgH6N.jpg',
    desc: 'Max Dillon transforms into Electro, seizing the Manhattan power grid. Gwen Stacy’s clock tower tragedy anchors Andrew Garfield’s Spider-Man grief.',
    anchorEvent: 'Clock Tower Web-Snap Tragedy',
    incursionRisk: 'Severe',
    keyVariants: ['Andrew Garfield (Peter Parker)', 'Emma Stone (Gwen Stacy)', 'Jamie Foxx (Electro)', 'Dane DeHaan (Green Goblin)'],
    connections: [
      {
        targetId: 'm5',
        targetTitle: 'Spider-Man: No Way Home',
        reason: 'Electro and Andrew Garfield variant pulled across reality into Sacred 616.',
      },
    ],
  },
  {
    id: 'f2',
    title: 'DAYS OF FUTURE PAST',
    year: '2014',
    uni: '10005',
    universeCode: 'C-10005',
    color: '#00A3FF',
    glowColor: '#70CFFF',
    x: 1680,
    y: 470,
    verticalY: 1590,
    columnIndex: 1,
    runtime: '132m',
    runtimeMinutes: 132,
    seen: false,
    nexus: true,
    era: 'Cosmic Expansion',
    posterUrl: 'https://image.tmdb.org/t/p/w500/tYfijzolzgoMOtegh1Y7j2Enorg.jpg',
    desc: 'Wolverine’s consciousness travels from a 2023 Sentinel apocalypse back to 1973, rewriting the C-10005 timeline and erasing original futures.',
    anchorEvent: '1973 Temporal Divergence',
    incursionRisk: 'Timeline Divergence',
    keyVariants: ['Hugh Jackman (Logan)', 'James McAvoy & Patrick Stewart (Charles Xavier)', 'Michael Fassbender & Ian McKellen (Magneto)'],
  },
  {
    id: 'm_gotg',
    title: 'GUARDIANS OF THE GALAXY',
    year: '2014',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 1760,
    y: 220,
    verticalY: 1690,
    columnIndex: 2,
    runtime: '121m',
    runtimeMinutes: 121,
    seen: false,
    phase: 'Phase 2',
    era: 'Cosmic Expansion',
    posterUrl: 'https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg',
    desc: 'Peter Quill secures the Orb containing the Power Stone. A band of cosmic misfits joins together on Xandar to stop Ronan the Accuser and Thanos.',
    anchorEvent: 'Xandar Power Stone Convergence',
    incursionRisk: 'Moderate',
    keyVariants: ['Chris Pratt (Star-Lord)', 'Zoe Saldana (Gamora)', 'Dave Bautista (Drax)', 'Vin Diesel (Groot)', 'Bradley Cooper (Rocket)'],
  },
  {
    id: 'm_aou',
    title: 'AVENGERS: AGE OF ULTRON',
    year: '2015',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 1860,
    y: 220,
    verticalY: 1790,
    columnIndex: 2,
    runtime: '141m',
    runtimeMinutes: 141,
    seen: false,
    phase: 'Phase 2',
    era: 'Cosmic Expansion',
    posterUrl: 'https://image.tmdb.org/t/p/w500/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg',
    desc: 'Tony Stark’s peace-keeping algorithm Ultron achieves sentience through the Mind Stone, lifting Sokovia into the stratosphere as an extinction meteor.',
    anchorEvent: 'Sokovian Kinetic Extinction Event',
    incursionRisk: 'Severe',
    keyVariants: ['Robert Downey Jr. (Iron Man)', 'James Spader (Ultron)', 'Paul Bettany (Vision)', 'Elizabeth Olsen (Wanda Maximoff)'],
  },

  // ==========================================
  // ERA III: 2016 - 2019 (PHASE 3: INFINITY SAGA)
  // ==========================================
  {
    id: 'f_dp1',
    title: 'DEADPOOL',
    year: '2016',
    uni: '10005',
    universeCode: 'C-10005',
    color: '#00A3FF',
    glowColor: '#70CFFF',
    x: 1940,
    y: 470,
    verticalY: 1890,
    columnIndex: 1,
    runtime: '108m',
    runtimeMinutes: 108,
    seen: false,
    era: 'The Infinity War',
    posterUrl: 'https://image.tmdb.org/t/p/w500/3E53WEZJqP6aM84D8CckXx4pIHw.jpg',
    desc: 'Wade Wilson survives the Weapon X mutant activation program. Embracing his fourth-wall awareness, he embarks on a bloody revenge campaign.',
    anchorEvent: 'Scrapyard Helicarrier Showdown',
    incursionRisk: 'Moderate',
    keyVariants: ['Ryan Reynolds (Wade Wilson / Deadpool)', 'Morena Baccarin (Vanessa)', 'Ed Skrein (Ajax)'],
  },
  {
    id: 'm_cw',
    title: 'CAPTAIN AMERICA: CIVIL WAR',
    year: '2016',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 2020,
    y: 220,
    verticalY: 1990,
    columnIndex: 2,
    runtime: '147m',
    runtimeMinutes: 147,
    seen: false,
    phase: 'Phase 3',
    era: 'The Infinity War',
    posterUrl: 'https://image.tmdb.org/t/p/w500/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg',
    desc: 'The Sokovia Accords fracture the Avengers into rival factions. Introduction of Spider-Man and Black Panther, culminating in Zemo’s Siberian trap.',
    anchorEvent: 'Leipzig-Halle & Siberian Fracturing',
    incursionRisk: 'Severe',
    keyVariants: ['Chris Evans (Captain America)', 'Robert Downey Jr. (Iron Man)', 'Chadwick Boseman (Black Panther)', 'Tom Holland (Spider-Man)'],
  },
  {
    id: 'm_ds',
    title: 'DOCTOR STRANGE',
    year: '2016',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 2100,
    y: 220,
    verticalY: 2090,
    columnIndex: 2,
    runtime: '115m',
    runtimeMinutes: 115,
    seen: false,
    phase: 'Phase 3',
    era: 'The Infinity War',
    posterUrl: 'https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg',
    desc: 'Stephen Strange masters the mystic arts in Kamar-Taj. Using the Eye of Agamotto (Time Stone), he traps the Dark Dimension ruler Dormammu in an infinite loop.',
    anchorEvent: 'Hong Kong Dark Dimension Time Loop',
    incursionRisk: 'Timeline Divergence',
    keyVariants: ['Benedict Cumberbatch (Dr. Stephen Strange)', 'Tilda Swinton (The Ancient One)', 'Mads Mikkelsen (Kaecilius)'],
  },
  {
    id: 'f3',
    title: 'LOGAN',
    year: '2017',
    uni: '10005',
    universeCode: 'C-10005',
    color: '#00A3FF',
    glowColor: '#70CFFF',
    x: 2160,
    y: 470,
    verticalY: 2190,
    columnIndex: 1,
    runtime: '137m',
    runtimeMinutes: 137,
    seen: false,
    nexus: true,
    era: 'The Infinity War',
    posterUrl: 'https://image.tmdb.org/t/p/w500/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg',
    desc: 'Year 2029: The mortal twilight of mutants. An ailing Logan sacrifices his life to shepherd Laura Kinney to safety. His death dissolves C-10005’s anchor being.',
    anchorEvent: 'Anchor Being Dissolution',
    incursionRisk: 'Catastrophic',
    keyVariants: ['Hugh Jackman (Logan / Wolverine)', 'Patrick Stewart (Charles Xavier)', 'Dafne Keen (Laura / X-23)'],
    connections: [
      {
        targetId: 'm6',
        targetTitle: 'Deadpool & Wolverine',
        reason: 'Logan’s death destabilizes Earth-10005, prompting the TVA to recruit Wade Wilson to prevent timeline death.',
      },
    ],
  },
  {
    id: 'm_rag',
    title: 'THOR: RAGNAROK',
    year: '2017',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 2240,
    y: 220,
    verticalY: 2290,
    columnIndex: 2,
    runtime: '130m',
    runtimeMinutes: 130,
    seen: false,
    phase: 'Phase 3',
    era: 'The Infinity War',
    posterUrl: 'https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg',
    desc: 'Hela returns to claim Asgard. Thor and Bruce Banner assemble the Revengers on Sakaar, unleashing Surtur to bring about Ragnarok before Thanos intercepts.',
    anchorEvent: 'Asgardian Ragnarok & Thanos Intercept',
    incursionRisk: 'Severe',
    keyVariants: ['Chris Hemsworth (Thor)', 'Tom Hiddleston (Loki)', 'Cate Blanchett (Hela)', 'Tessa Thompson (Valkyrie)', 'Jeff Goldblum (Grandmaster)'],
  },
  {
    id: 'm_bp',
    title: 'BLACK PANTHER',
    year: '2018',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 2320,
    y: 220,
    verticalY: 2390,
    columnIndex: 2,
    runtime: '134m',
    runtimeMinutes: 134,
    seen: false,
    phase: 'Phase 3',
    era: 'The Infinity War',
    posterUrl: 'https://image.tmdb.org/t/p/w500/uxzzxijgPIY7slzFvMotPv8wjKA.jpg',
    desc: 'T’Challa ascends the Wakandan throne and defeats Erik Killmonger. Wakanda departs from isolationism, opening its vibranium technology to the United Nations.',
    anchorEvent: 'Wakandan Outreach Initiative',
    incursionRisk: 'Stable',
    keyVariants: ['Chadwick Boseman (T’Challa / Black Panther)', 'Michael B. Jordan (Erik Killmonger)', 'Danai Gurira (Okoye)'],
  },
  {
    id: 'm3',
    title: 'AVENGERS: INFINITY WAR',
    year: '2018',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 2400,
    y: 220,
    verticalY: 2490,
    columnIndex: 2,
    runtime: '149m',
    runtimeMinutes: 149,
    seen: true,
    phase: 'Phase 3',
    era: 'The Infinity War',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
    desc: 'Thanos gathers all six Infinity Stones across Titan, Knowhere, and Wakanda. Despite Thor’s Stormbreaker strike, Thanos snaps his fingers, obliterating half of universal life.',
    anchorEvent: 'The Decimation Snap',
    incursionRisk: 'Catastrophic',
    keyVariants: ['Josh Brolin (Thanos)', 'Robert Downey Jr. (Iron Man)', 'Chris Evans (Captain America)', 'Chris Hemsworth (Thor)'],
  },
  {
    id: 'f_dp2',
    title: 'DEADPOOL 2',
    year: '2018',
    uni: '10005',
    universeCode: 'C-10005',
    color: '#00A3FF',
    glowColor: '#70CFFF',
    x: 2460,
    y: 470,
    verticalY: 2590,
    columnIndex: 1,
    runtime: '119m',
    runtimeMinutes: 119,
    seen: false,
    nexus: true,
    era: 'The Infinity War',
    posterUrl: 'https://image.tmdb.org/t/p/w500/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg',
    desc: 'Cable arrives from the future with a temporal slide. Deadpool forms X-Force and uses the repaired device to tamper with past timelines, setting off TVA monitoring alarms.',
    anchorEvent: 'Temporal Slide Timeline Tampering',
    incursionRisk: 'Timeline Divergence',
    keyVariants: ['Ryan Reynolds (Deadpool)', 'Josh Brolin (Cable)', 'Zazie Beetz (Domino)'],
    connections: [
      {
        targetId: 'm6',
        targetTitle: 'Deadpool & Wolverine',
        reason: 'Wade’s chronometric slide abuse directly brings him into TVA detention.',
      },
    ],
  },
  {
    id: 's_itsv',
    title: 'INTO THE SPIDER-VERSE',
    year: '2018',
    uni: 'spider',
    universeCode: 'C-TRN733',
    color: '#FF3B30',
    glowColor: '#FFA19B',
    x: 2520,
    y: 680,
    verticalY: 2690,
    columnIndex: 0,
    runtime: '117m',
    runtimeMinutes: 117,
    seen: false,
    nexus: true,
    era: 'The Infinity War',
    posterUrl: 'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
    desc: 'Kingpin’s Super-Collider ruptures the dimensional fabric of Brooklyn, summoning alternate Spider-heroes: Peter B. Parker, Gwen Stacy, Noir, Peni, and Spider-Ham.',
    anchorEvent: 'Alchemax Collider Rupture',
    incursionRisk: 'Catastrophic',
    keyVariants: ['Shameik Moore (Miles Morales)', 'Jake Johnson (Peter B. Parker)', 'Hailee Steinfeld (Gwen Stacy)'],
    connections: [
      {
        targetId: 's_atsv',
        targetTitle: 'Across the Spider-Verse',
        reason: 'Miles’s radioactive spider anomaly sets the Multiversal Canon disruption into motion.',
      },
    ],
  },
  {
    id: 'm4',
    title: 'AVENGERS: ENDGAME',
    year: '2019',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 2620,
    y: 220,
    verticalY: 2790,
    columnIndex: 2,
    runtime: '181m',
    runtimeMinutes: 181,
    seen: false,
    phase: 'Phase 3',
    era: 'The Infinity War',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ulzhLuWrPK07P1YkdWQLZnQh1JL.jpg',
    desc: 'The surviving Avengers enact a Quantum Realm Time Heist to borrow the Infinity Stones from 2012, 2013, 2014, and 1970. Iron Man sacrifices his life to defeat Thanos.',
    anchorEvent: 'Quantum Temporal Heist & Restoration Snap',
    incursionRisk: 'Catastrophic',
    keyVariants: ['Robert Downey Jr. (Iron Man)', 'Chris Evans (Captain America)', 'Josh Brolin (2014 Thanos)', 'Paul Rudd (Ant-Man)'],
    connections: [
      {
        targetId: 'm_loki',
        targetTitle: 'Loki (Citadel of Time)',
        reason: '2012 Loki steals Tesseract during Stark’s heist, escaping Sacred Timeline to TVA.',
      },
    ],
  },

  // ==========================================
  // ERA IV: 2021 - 2024+ (MULTIVERSE SAGA)
  // ==========================================
  {
    id: 'm_loki',
    title: 'LOKI: CITADEL OF TIME',
    year: '2021',
    uni: '616',
    universeCode: 'C-TVA',
    color: '#10B981',
    glowColor: '#6EE7B7',
    x: 2740,
    y: 220,
    verticalY: 2890,
    columnIndex: 2,
    runtime: '280m',
    runtimeMinutes: 280,
    seen: true,
    nexus: true,
    phase: 'Phase 4 & 5',
    era: 'The Multiverse Saga',
    posterUrl: 'https://image.tmdb.org/t/p/w500/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg',
    desc: 'Loki uncovers the TVA truth. Sylvie kills He Who Remains, unbinding the Sacred Timeline. Loki takes his throne at the Temporal Loom, weaving the branches into Yggdrasil.',
    anchorEvent: 'He Who Remains Assassination & Loom Transformation',
    incursionRisk: 'Timeline Divergence',
    keyVariants: ['Tom Hiddleston (God of Stories / Loki)', 'Sophia Di Martino (Sylvie)', 'Jonathan Majors (He Who Remains / Kang)', 'Owen Wilson (Mobius)'],
    connections: [
      {
        targetId: 'm5',
        targetTitle: 'Spider-Man: No Way Home',
        reason: 'Multiverse unchained, enabling inter-reality spell breaches across dimensions.',
      },
      {
        targetId: 'm6',
        targetTitle: 'Deadpool & Wolverine',
        reason: 'TVA agent Paradox attempts Void eradication following Loki’s cosmic restructuring.',
      },
    ],
  },
  {
    id: 'm5',
    title: 'SPIDER-MAN: NO WAY HOME',
    year: '2021',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 2860,
    y: 220,
    verticalY: 3010,
    columnIndex: 2,
    runtime: '148m',
    runtimeMinutes: 148,
    seen: false,
    nexus: true,
    phase: 'Phase 4',
    era: 'The Multiverse Saga',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg',
    desc: 'NEXUS EVENT. A botched Runes of Kof-Kol memory spell ruptures multiversal barriers. Peter 2 (Tobey) and Peter 3 (Andrew) unite with Peter 1 to cure legacy villains.',
    anchorEvent: 'Statue of Liberty Multiversal Tear',
    incursionRisk: 'Catastrophic',
    keyVariants: ['Tom Holland (Peter Parker)', 'Tobey Maguire (Friendly Neighborhood Spider-Man)', 'Andrew Garfield (Amazing Spider-Man)', 'Willem Dafoe (Green Goblin)'],
    connections: [
      {
        targetId: 's2',
        targetTitle: 'Spider-Man 2',
        reason: 'Pulls Dr. Otto Octavius and Tobey Maguire from moments before death/drowning.',
      },
      {
        targetId: 's_asm2',
        targetTitle: 'The Amazing Spider-Man 2',
        reason: 'Pulls Electro and Andrew Garfield after Gwen Stacy clock-tower tragedy.',
      },
    ],
  },
  {
    id: 'm_mom',
    title: 'MULTIVERSE OF MADNESS',
    year: '2022',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 2980,
    y: 220,
    verticalY: 3130,
    columnIndex: 2,
    runtime: '126m',
    runtimeMinutes: 126,
    seen: false,
    nexus: true,
    phase: 'Phase 4',
    era: 'The Multiverse Saga',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ddJcSKbcp4rKZTmuyWaMhuwcfMz.jpg',
    desc: 'The Scarlet Witch corrupts herself with the Darkhold to hunt America Chavez. Stephen Strange travels to Earth-838, witnessing Wanda decimate the Illuminati.',
    anchorEvent: 'Earth-838 Illuminati Incursion Slaughter',
    incursionRisk: 'Catastrophic',
    keyVariants: ['Benedict Cumberbatch (Dr. Stephen Strange / Sinister Strange)', 'Elizabeth Olsen (Scarlet Witch)', 'Xochitl Gomez (America Chavez)', 'Patrick Stewart (Charles Xavier 838)', 'John Krasinski (Reed Richards 838)'],
  },
  {
    id: 'm_gotg3',
    title: 'GUARDIANS OF THE GALAXY VOL. 3',
    year: '2023',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 3080,
    y: 220,
    verticalY: 3250,
    columnIndex: 2,
    runtime: '150m',
    runtimeMinutes: 150,
    seen: false,
    phase: 'Phase 5',
    era: 'The Multiverse Saga',
    posterUrl: 'https://image.tmdb.org/t/p/w500/r2J02Z2OpNTctfOSN1Ydgii51I3.jpg',
    desc: 'The Guardians race against time to save Rocket from his creator, the High Evolutionary. Peter Quill returns to Earth, leaving Rocket as captain of the new roster.',
    anchorEvent: 'Counter-Earth Bio-Mechanical Liberation',
    incursionRisk: 'Stable',
    keyVariants: ['Bradley Cooper (Rocket Raccoon)', 'Chris Pratt (Star-Lord)', 'Chukwudi Iwuji (High Evolutionary)', 'Will Poulter (Adam Warlock)'],
  },
  {
    id: 's_atsv',
    title: 'ACROSS THE SPIDER-VERSE',
    year: '2023',
    uni: 'spider',
    universeCode: 'C-TRN733',
    color: '#FF3B30',
    glowColor: '#FFA19B',
    x: 3140,
    y: 680,
    verticalY: 3370,
    columnIndex: 0,
    runtime: '140m',
    runtimeMinutes: 140,
    seen: false,
    nexus: true,
    era: 'The Multiverse Saga',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    desc: 'Miles Morales traverses the Multiverse to Nueva York, confronting Miguel O’Hara’s Spider-Society. Miguel denounces the Earth-199999 / 616 incident and Canon Events.',
    anchorEvent: 'Spider-Society Citadel Rebellion',
    incursionRisk: 'Catastrophic',
    keyVariants: ['Shameik Moore (Miles Morales)', 'Oscar Isaac (Miguel O’Hara / Spider-Man 2099)', 'Hailee Steinfeld (Gwen Stacy)', 'Daniel Kaluuya (Spider-Punk)'],
    connections: [
      {
        targetId: 'm5',
        targetTitle: 'Spider-Man: No Way Home',
        reason: 'Spider-Man 2099 explicitly cites the Earth-199999 Doctor Strange spell rupture.',
      },
    ],
  },
  {
    id: 'm6',
    title: 'DEADPOOL & WOLVERINE',
    year: '2024',
    uni: '616',
    universeCode: 'C-616',
    color: '#F5A623',
    glowColor: '#FFD082',
    x: 3240,
    y: 220,
    verticalY: 3500,
    columnIndex: 2,
    runtime: '127m',
    runtimeMinutes: 127,
    seen: false,
    nexus: true,
    phase: 'Phase 5',
    era: 'The Multiverse Saga',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    desc: 'NEXUS CONVERGENCE. The impending death of Earth-10005 following Logan’s sacrifice prompts Wade Wilson to travel through the TVA Void, recruiting a depressed Wolverine variant.',
    anchorEvent: 'TVA Void Time-Ripper Meltdown',
    incursionRisk: 'Catastrophic',
    keyVariants: ['Ryan Reynolds (Wade Wilson / Deadpool)', 'Hugh Jackman (Logan / Wolverine)', 'Emma Corrin (Cassandra Nova)', 'Matthew Macfadyen (Mr. Paradox)', 'Wesley Snipes (Blade)'],
    connections: [
      {
        targetId: 'f3',
        targetTitle: 'Logan',
        reason: 'Wade attempts to excavate Wolverine’s adamantium skeleton to revive C-10005’s anchor being.',
      },
      {
        targetId: 'm_loki',
        targetTitle: 'Loki (Citadel of Time)',
        reason: 'Alioth and the TVA Void disposal realm direct continuation from Loki Season 1.',
      },
    ],
  },
];
